/*
 * @Author: Will Cheng (will.cheng@efctw.com)
 * @Date: 2024-10-22 10:07:45
 * @LastEditors: Will Cheng (will.cheng@efctw.com)
 * @LastEditTime: 2024-10-29 11:11:43
 * @FilePath: /PoseidonAI-Client/src/utils/LogActions.ts
 */
export enum LogActionDataset {
  CREATE_DATASET_FORM_MOUNT = 'CREATE_DATASET_FORM_MOUNT',
  CREATE_DATASET_UPLOAD_JSON_SUCCESS = 'CREATE_DATASET_UPLOAD_JSON_SUCCESS',
  CREATE_DATASET_UPLOAD_JSON_FAILURE = 'CREATE_DATASET_UPLOAD_JSON_FAILURE',
  CREATE_DATASET_UPLOAD_IMAGE_SUCCESS = 'CREATE_DATASET_UPLOAD_IMAGE_SUCCESS',
  CREATE_DATASET_UPLOAD_IMAGE_FAILURE = 'CREATE_DATASET_UPLOAD_IMAGE_FAILURE',
  CREATE_DATASET_SUBMIT_START = 'CREATE_DATASET_SUBMIT_START',
  CREATE_DATASET_SUBMIT_SUCCESS = 'CREATE_DATASET_SUBMIT_SUCCESS',
  CREATE_DATASET_SUBMIT_FAILURE = 'CREATE_DATASET_SUBMIT_FAILURE',
  CREATE_DATASET_DETECT_TYPE_CHANGE = 'CREATE_DATASET_DETECT_TYPE_CHANGE',
  CREATE_DATASET_UPLOAD_ZIP_FAILURE = 'CREATE_DATASET_UPLOAD_ZIP_FAILURE',
  CREATE_DATASET_UPLOAD_ZIP_SUCCESS = 'CREATE_DATASET_UPLOAD_ZIP_SUCCESS',
  CREATE_DATASET_FORM_VALIDATION_FAILURE = 'CREATE_DATASET_FORM_VALIDATION_FAILURE',
  DATASET_DETAILS_COMPONENT_MOUNT = 'DATASET_DETAILS_COMPONENT_MOUNT',
  DATASET_FETCH_VISUALIZED_FILES = 'DATASET_FETCH_VISUALIZED_FILES',
  DATASET_DISPLAY_IMAGE = 'DATASET_DISPLAY_IMAGE',
  DATASET_START_VISUALIZATION = 'DATASET_START_VISUALIZATION',
  DATASET_VISUALIZATION_PROGRESS = 'DATASET_VISUALIZATION_PROGRESS',
  DATASET_VISUALIZATION_SUCCESS = 'DATASET_VISUALIZATION_SUCCESS',
  DATASET_VISUALIZATION_FAILURE = 'DATASET_VISUALIZATION_FAILURE',
  DATASET_FETCH_VISUALIZED_FILES_FAILURE = 'DATASET_FETCH_VISUALIZED_FILES_FAILURE',
  DATASET_HANDLE_VISUALIZATION_FAILURE = 'DATASET_HANDLE_VISUALIZATION_FAILURE',
  LIST_DATASETS_COMPONENT_MOUNT = 'LIST_DATASETS_COMPONENT_MOUNT',
  LIST_DATASETS_VIEW_DETAILS = 'LIST_DATASETS_VIEW_DETAILS',
  LIST_DATASETS_DELETE_CONFIRM = 'LIST_DATASETS_DELETE_CONFIRM',
  LIST_DATASETS_DELETE_START = 'LIST_DATASETS_DELETE_START',
  LIST_DATASETS_DELETE_SUCCESS = 'LIST_DATASETS_DELETE_SUCCESS',
  LIST_DATASETS_DELETE_FAILURE = 'LIST_DATASETS_DELETE_FAILURE',
}

export enum LogActionConfig {
  CREATE_CONFIGURATION_COMPONENT_MOUNT = 'CREATE_CONFIGURATION_COMPONENT_MOUNT',
  CREATE_CONFIGURATION_SELECT_FRAMEWORK = 'CREATE_CONFIGURATION_SELECT_FRAMEWORK',
  CREATE_CONFIGURATION_SUBMIT_START = 'CREATE_CONFIGURATION_SUBMIT_START',
  CREATE_CONFIGURATION_SUBMIT_SUCCESS = 'CREATE_CONFIGURATION_SUBMIT_SUCCESS',
  CREATE_CONFIGURATION_SUBMIT_FAILURE = 'CREATE_CONFIGURATION_SUBMIT_FAILURE',
  CREATE_CONFIGURATION_SUBMIT_NETWORK_ERROR = 'CREATE_CONFIGURATION_SUBMIT_NETWORK_ERROR',
  LIST_CONFIGURATIONS_COMPONENT_MOUNT = 'LIST_CONFIGURATIONS_COMPONENT_MOUNT',
  LIST_CONFIGURATIONS_VIEW_DETAILS = 'LIST_CONFIGURATIONS_VIEW_DETAILS',
  LIST_CONFIGURATIONS_DELETE_START = 'LIST_CONFIGURATIONS_DELETE_START',
  LIST_CONFIGURATIONS_DELETE_SUCCESS = 'LIST_CONFIGURATIONS_DELETE_SUCCESS',
  LIST_CONFIGURATIONS_DELETE_FAILURE = 'LIST_CONFIGURATIONS_DELETE_FAILURE',
}

export enum LogActionCreateTask {
  // TrainingConfigForm related
  CREATE_CONFIGURATION_COMPONENT_MOUNT = 'CREATE_CONFIGURATION_COMPONENT_MOUNT',
  CREATE_CONFIGURATION_SELECT_FRAMEWORK = 'CREATE_CONFIGURATION_SELECT_FRAMEWORK',
  CREATE_CONFIGURATION_SUBMIT_START = 'CREATE_CONFIGURATION_SUBMIT_START',
  CREATE_CONFIGURATION_SUBMIT_SUCCESS = 'CREATE_CONFIGURATION_SUBMIT_SUCCESS',
  CREATE_CONFIGURATION_SUBMIT_FAILURE = 'CREATE_CONFIGURATION_SUBMIT_FAILURE',
  CREATE_CONFIGURATION_SUBMIT_NETWORK_ERROR = 'CREATE_CONFIGURATION_SUBMIT_NETWORK_ERROR',
  LIST_CONFIGURATIONS_COMPONENT_MOUNT = 'LIST_CONFIGURATIONS_COMPONENT_MOUNT',
  LIST_CONFIGURATIONS_VIEW_DETAILS = 'LIST_CONFIGURATIONS_VIEW_DETAILS',
  LIST_CONFIGURATIONS_DELETE_START = 'LIST_CONFIGURATIONS_DELETE_START',
  LIST_CONFIGURATIONS_DELETE_SUCCESS = 'LIST_CONFIGURATIONS_DELETE_SUCCESS',
  LIST_CONFIGURATIONS_DELETE_FAILURE = 'LIST_CONFIGURATIONS_DELETE_FAILURE',

  // 新增的日志操作与 TrainingConfigForm 相关
  TRAINING_CONFIG_FORM_COMPONENT_MOUNT = 'TRAINING_CONFIG_FORM_COMPONENT_MOUNT',
  TRAINING_CONFIG_SELECT_ALGORITHM = 'TRAINING_CONFIG_SELECT_ALGORITHM',
  TRAINING_CONFIG_SELECT_DATASET = 'TRAINING_CONFIG_SELECT_DATASET',
  TRAINING_CONFIG_SELECT_CONFIG = 'TRAINING_CONFIG_SELECT_CONFIG',
  TRAINING_CONFIG_SELECT_GPU = 'TRAINING_CONFIG_SELECT_GPU',
  TRAINING_CONFIG_SUBMIT_START = 'TRAINING_CONFIG_SUBMIT_START',
  TRAINING_CONFIG_SUBMIT_SUCCESS = 'TRAINING_CONFIG_SUBMIT_SUCCESS',
  TRAINING_CONFIG_SUBMIT_FAILURE = 'TRAINING_CONFIG_SUBMIT_FAILURE',
  TRAINING_CONFIG_VIEW_DATASET_DETAILS = 'TRAINING_CONFIG_VIEW_DATASET_DETAILS',
  TRAINING_CONFIG_VIEW_CONFIG_DETAILS = 'TRAINING_CONFIG_VIEW_CONFIG_DETAILS',
  TRAINING_CONFIG_RESET_FORM = 'TRAINING_CONFIG_RESET_FORM',
  TRAINING_CONFIG_SELECT_EPOCH = 'TRAINING_CONFIG_SELECT_EPOCH',
  TRAINING_CONFIG_SELECT_TRAIN_VAL_RATIO = 'TRAINING_CONFIG_SELECT_TRAIN_VAL_RATIO',
}

export enum LogActionTrainingTask {
  TASKLIST_COMPONENT_MOUNT = 'TASKLIST_COMPONENT_MOUNT',
  TASKLIST_VIEW_DETAILS = 'TASKLIST_VIEW_DETAILS',
  TASKLIST_DELETE_START = 'TASKLIST_DELETE_START',
  TASKLIST_DELETE_SUCCESS = 'TASKLIST_DELETE_SUCCESS',
  TASKLIST_DELETE_FAILURE = 'TASKLIST_DELETE_FAILURE',
  MODEL_TRAINING_COMPONENT_MOUNT = 'MODEL_TRAINING_COMPONENT_MOUNT',
  MODEL_TRAINING_START = 'MODEL_TRAINING_START',
  MODEL_TRAINING_RESTART = 'MODEL_TRAINING_RESTART',
  MODEL_TRAINING_STOP = 'MODEL_TRAINING_STOP',
  MODEL_TRAINING_PROGRESS_FETCH = 'MODEL_TRAINING_PROGRESS_FETCH',
  MODEL_TRAINING_SUCCESS = 'MODEL_TRAINING_SUCCESS',
  MODEL_TRAINING_FAILURE = 'MODEL_TRAINING_FAILURE',
  MODEL_TRAINING_ERROR = 'MODEL_TRAINING_ERROR',
  TASK_DETAILS_PAGE_LOAD = 'TASK_DETAILS_PAGE_LOAD',
  TASK_DETAILS_FETCH_SUCCESS = 'TASK_DETAILS_FETCH_SUCCESS',
  TASK_DETAILS_FETCH_FAILURE = 'TASK_DETAILS_FETCH_FAILURE',
  TASK_DETAILS_TAB_SWITCH = 'TASK_DETAILS_TAB_SWITCH',
  TASK_DETAILS_TAB_LOAD_TRAINING = 'TASK_DETAILS_TAB_LOAD_TRAINING',
  TASK_DETAILS_TAB_LOAD_EVAL = 'TASK_DETAILS_TAB_LOAD_EVAL',
  TASK_DETAILS_TAB_LOAD_VISUALIZE = 'TASK_DETAILS_TAB_LOAD_VISUALIZE',
  TASK_DETAILS_TAB_LOAD_EXPORT = 'TASK_DETAILS_TAB_LOAD_EXPORT',
}

export enum LogActionEvalTask {
  EVAL_TASK_COMPONENT_MOUNT = 'EVAL_TASK_COMPONENT_MOUNT', // 组件加载
  EVAL_TASK_START = 'EVAL_TASK_START', // 开始评估
  EVAL_TASK_RESTART = 'EVAL_TASK_RESTART', // 重新评估
  EVAL_TASK_PROGRESS_FETCH = 'EVAL_TASK_PROGRESS_FETCH', // 获取评估进度
  EVAL_TASK_SUCCESS = 'EVAL_TASK_SUCCESS', // 评估成功
  EVAL_TASK_FAILURE = 'EVAL_TASK_FAILURE', // 评估失败
  EVAL_TASK_ERROR = 'EVAL_TASK_ERROR', // 评估错误
  EVAL_TASK_FETCH_RESULT = 'EVAL_TASK_FETCH_RESULT', // 获取评估结果
}

export enum LogActionVisTask {
  VIS_TASK_COMPONENT_MOUNT = 'VIS_TASK_COMPONENT_MOUNT', // 组件挂载
  VIS_TASK_START = 'VIS_TASK_START', // 开始可视化
  VIS_TASK_RESTART = 'VIS_TASK_RESTART', // 重新可视化
  VIS_TASK_PROGRESS_FETCH = 'VIS_TASK_PROGRESS_FETCH', // 获取可视化进度
  VIS_TASK_SUCCESS = 'VIS_TASK_SUCCESS', // 可视化成功
  VIS_TASK_FAILURE = 'VIS_TASK_FAILURE', // 可视化失败
  VIS_TASK_ERROR = 'VIS_TASK_ERROR', // 可视化错误
  VIS_TASK_FETCH_RESULT = 'VIS_TASK_FETCH_RESULT', // 获取可视化结果
}

export enum LogActionExportTask {
  EXPORT_TASK_COMPONENT_MOUNT = 'EXPORT_TASK_COMPONENT_MOUNT', // 组件挂载
  EXPORT_TASK_START = 'EXPORT_TASK_START', // 开始导出模型
  EXPORT_TASK_PROGRESS_FETCH = 'EXPORT_TASK_PROGRESS_FETCH', // 获取导出进度
  EXPORT_TASK_SUCCESS = 'EXPORT_TASK_SUCCESS', // 导出成功
  EXPORT_TASK_FAILURE = 'EXPORT_TASK_FAILURE', // 导出失败
  EXPORT_TASK_ERROR = 'EXPORT_TASK_ERROR', // 导出错误
}
